# Learn more about configuring your app at https://shopify.dev/docs/apps/build/cli/configuration

client_id = "d7d31726e1d03bf022e016021f595095"
name = "first-extension"
handle = "first-extension-19"
application_url = "https://beautyai.duckdns.org/app_entry/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
# Use the latest stable API version
api_version = "2025-07"

[access_scopes]
# Add more scopes later if needed (e.g., read_products)
scopes = "write_online_store_pages,read_products,write_products,write_content,read_online_store_pages,read_online_store_navigation,write_online_store_navigation"


[auth]
# Matches your Django callback URL
redirect_urls = [
  "https://beautyai.duckdns.org/auth/callback/"
]
